//
//  AlertTests.swift
//  AlertFactoryTests
//
//  Created by Andrew Florjancic on 8/10/24.
//  Copyright © 2024 Andrew Florjancic. All rights reserved.
//

import XCTest
@testable import AlertFactory

final class AlertTests: XCTestCase {
    
    var sut: UIAlertController!
    
    func testCreateAlerts() throws {

        sut = TestAlerts.springLoadedAlertDefaultSeverityWithMessage.create()
        XCTAssertEqual(sut.title, "Spring Loaded - Alert - Default Severity - With Message")
        XCTAssertEqual(sut.isSpringLoaded, true)
        XCTAssertEqual(sut.preferredStyle, .alert)
        XCTAssertEqual(sut.severity, .default)
        XCTAssertEqual(sut.message, "Sample message")
        XCTAssertEqual(sut.textFields?.count, 0)
        XCTAssertEqual(sut.actions.count, 0)
        XCTAssertEqual(sut.preferredAction, nil)
        XCTAssertEqual(sut.view.accessibilityIdentifier, String(describing: TestAlerts.springLoadedAlertDefaultSeverityWithMessage))
        
        sut = TestAlerts.springLoadedAlertDefaultSeverityWithoutMessage.create()
        XCTAssertEqual(sut.title, "Spring Loaded - Alert - Default Severity - Without Message")
        XCTAssertEqual(sut.isSpringLoaded, true)
        XCTAssertEqual(sut.preferredStyle, .alert)
        XCTAssertEqual(sut.severity, .default)
        XCTAssertEqual(sut.message, nil)
        XCTAssertEqual(sut.textFields?.count, 0)
        XCTAssertEqual(sut.actions.count, 0)
        XCTAssertEqual(sut.preferredAction, nil)
        XCTAssertEqual(sut.view.accessibilityIdentifier, String(describing: TestAlerts.springLoadedAlertDefaultSeverityWithoutMessage))
        
        sut = TestAlerts.springLoadedActionSheetDefaultSeverityWithMessage.create()
        XCTAssertEqual(sut.title, "Spring Loaded - Action Sheet - Default Severity - With Message")
        XCTAssertEqual(sut.isSpringLoaded, true)
        XCTAssertEqual(sut.preferredStyle, .actionSheet)
        XCTAssertEqual(sut.severity, .default)
        XCTAssertEqual(sut.message, "Sample message")
        XCTAssertEqual(sut.textFields?.count, 0)
        XCTAssertEqual(sut.actions.count, 0)
        XCTAssertEqual(sut.preferredAction, nil)
        XCTAssertEqual(sut.view.accessibilityIdentifier, String(describing: TestAlerts.springLoadedActionSheetDefaultSeverityWithMessage))
        
        sut = TestAlerts.springLoadedActionSheetDefaultSeverityWithoutMessage.create()
        XCTAssertEqual(sut.title, "Spring Loaded - Action Sheet - Default Severity - Without Message")
        XCTAssertEqual(sut.isSpringLoaded, true)
        XCTAssertEqual(sut.preferredStyle, .actionSheet)
        XCTAssertEqual(sut.severity, .default)
        XCTAssertEqual(sut.message, nil)
        XCTAssertEqual(sut.textFields?.count, 0)
        XCTAssertEqual(sut.actions.count, 0)
        XCTAssertEqual(sut.preferredAction, nil)
        XCTAssertEqual(sut.view.accessibilityIdentifier, String(describing: TestAlerts.springLoadedActionSheetDefaultSeverityWithoutMessage))
        
        sut = TestAlerts.springLoadedAlertCriticalSeverityWithMessage.create()
        XCTAssertEqual(sut.title, "Spring Loaded - Alert - Critical Severity - With Message")
        XCTAssertEqual(sut.isSpringLoaded, true)
        XCTAssertEqual(sut.preferredStyle, .alert)
        XCTAssertEqual(sut.severity, .critical)
        XCTAssertEqual(sut.message, "Sample message")
        XCTAssertEqual(sut.textFields?.count, 0)
        XCTAssertEqual(sut.actions.count, 0)
        XCTAssertEqual(sut.preferredAction, nil)
        XCTAssertEqual(sut.view.accessibilityIdentifier, String(describing: TestAlerts.springLoadedAlertCriticalSeverityWithMessage))
        
        sut = TestAlerts.springLoadedAlertCriticalSeverityWithoutMessage.create()
        XCTAssertEqual(sut.title, "Spring Loaded - Alert - Critical Severity - Without Message")
        XCTAssertEqual(sut.isSpringLoaded, true)
        XCTAssertEqual(sut.preferredStyle, .alert)
        XCTAssertEqual(sut.severity, .critical)
        XCTAssertEqual(sut.message, nil)
        XCTAssertEqual(sut.textFields?.count, 0)
        XCTAssertEqual(sut.actions.count, 0)
        XCTAssertEqual(sut.preferredAction, nil)
        XCTAssertEqual(sut.view.accessibilityIdentifier, String(describing: TestAlerts.springLoadedAlertCriticalSeverityWithoutMessage))
        
        sut = TestAlerts.springLoadedActionSheetCriticalSeverityWithMessage.create()
        XCTAssertEqual(sut.title, "Spring Loaded - Action Sheet - Critical Severity - With Message")
        XCTAssertEqual(sut.isSpringLoaded, true)
        XCTAssertEqual(sut.preferredStyle, .actionSheet)
        XCTAssertEqual(sut.severity, .critical)
        XCTAssertEqual(sut.message, "Sample message")
        XCTAssertEqual(sut.textFields?.count, 0)
        XCTAssertEqual(sut.actions.count, 0)
        XCTAssertEqual(sut.preferredAction, nil)
        XCTAssertEqual(sut.view.accessibilityIdentifier, String(describing: TestAlerts.springLoadedActionSheetCriticalSeverityWithMessage))
        
        sut = TestAlerts.springLoadedActionSheetCriticalSeverityWithoutMessage.create()
        XCTAssertEqual(sut.title, "Spring Loaded - Action Sheet - Critical Severity - Without Message")
        XCTAssertEqual(sut.isSpringLoaded, true)
        XCTAssertEqual(sut.preferredStyle, .actionSheet)
        XCTAssertEqual(sut.severity, .critical)
        XCTAssertEqual(sut.message, nil)
        XCTAssertEqual(sut.textFields?.count, 0)
        XCTAssertEqual(sut.actions.count, 0)
        XCTAssertEqual(sut.preferredAction, nil)
        XCTAssertEqual(sut.view.accessibilityIdentifier, String(describing: TestAlerts.springLoadedActionSheetCriticalSeverityWithoutMessage))
        
        sut = TestAlerts.nonSpringLoadedAlertDefaultSeverityWithMessage.create()
        XCTAssertEqual(sut.title, "Non Spring Loaded - Alert - Default Severity - With Message")
        XCTAssertEqual(sut.isSpringLoaded, false)
        XCTAssertEqual(sut.preferredStyle, .alert)
        XCTAssertEqual(sut.severity, .default)
        XCTAssertEqual(sut.message, "Sample message")
        XCTAssertEqual(sut.textFields?.count, 0)
        XCTAssertEqual(sut.actions.count, 0)
        XCTAssertEqual(sut.preferredAction, nil)
        XCTAssertEqual(sut.view.accessibilityIdentifier, String(describing: TestAlerts.nonSpringLoadedAlertDefaultSeverityWithMessage))
        
        sut = TestAlerts.nonSpringLoadedAlertDefaultSeverityWithoutMessage.create()
        XCTAssertEqual(sut.title, "Non Spring Loaded - Alert - Default Severity - Without Message")
        XCTAssertEqual(sut.isSpringLoaded, false)
        XCTAssertEqual(sut.preferredStyle, .alert)
        XCTAssertEqual(sut.severity, .default)
        XCTAssertEqual(sut.message, nil)
        XCTAssertEqual(sut.textFields?.count, 0)
        XCTAssertEqual(sut.actions.count, 0)
        XCTAssertEqual(sut.preferredAction, nil)
        XCTAssertEqual(sut.view.accessibilityIdentifier, String(describing: TestAlerts.nonSpringLoadedAlertDefaultSeverityWithoutMessage))
        
        sut = TestAlerts.nonSpringLoadedActionSheetDefaultSeverityWithMessage.create()
        XCTAssertEqual(sut.title, "Non Spring Loaded - Action Sheet - Default Severity - With Message")
        XCTAssertEqual(sut.isSpringLoaded, false)
        XCTAssertEqual(sut.preferredStyle, .actionSheet)
        XCTAssertEqual(sut.severity, .default)
        XCTAssertEqual(sut.message, "Sample message")
        XCTAssertEqual(sut.textFields?.count, 0)
        XCTAssertEqual(sut.actions.count, 0)
        XCTAssertEqual(sut.preferredAction, nil)
        XCTAssertEqual(sut.view.accessibilityIdentifier, String(describing: TestAlerts.nonSpringLoadedActionSheetDefaultSeverityWithMessage))
        
        sut = TestAlerts.nonSpringLoadedActionSheetDefaultSeverityWithoutMessage.create()
        XCTAssertEqual(sut.title, "Non Spring Loaded - Action Sheet - Default Severity - Without Message")
        XCTAssertEqual(sut.isSpringLoaded, false)
        XCTAssertEqual(sut.preferredStyle, .actionSheet)
        XCTAssertEqual(sut.severity, .default)
        XCTAssertEqual(sut.message, nil)
        XCTAssertEqual(sut.textFields?.count, 0)
        XCTAssertEqual(sut.actions.count, 0)
        XCTAssertEqual(sut.preferredAction, nil)
        XCTAssertEqual(sut.view.accessibilityIdentifier, String(describing: TestAlerts.nonSpringLoadedActionSheetDefaultSeverityWithoutMessage))
        
        sut = TestAlerts.nonSpringLoadedAlertCriticalSeverityWithMessage.create()
        XCTAssertEqual(sut.title, "Non Spring Loaded - Alert - Critical Severity - With Message")
        XCTAssertEqual(sut.isSpringLoaded, false)
        XCTAssertEqual(sut.preferredStyle, .alert)
        XCTAssertEqual(sut.severity, .critical)
        XCTAssertEqual(sut.message, "Sample message")
        XCTAssertEqual(sut.textFields?.count, 0)
        XCTAssertEqual(sut.actions.count, 0)
        XCTAssertEqual(sut.preferredAction, nil)
        XCTAssertEqual(sut.view.accessibilityIdentifier, String(describing: TestAlerts.nonSpringLoadedAlertCriticalSeverityWithMessage))
        
        sut = TestAlerts.nonSpringLoadedAlertCriticalSeverityWithoutMessage.create()
        XCTAssertEqual(sut.title, "Non Spring Loaded - Alert - Critical Severity - Without Message")
        XCTAssertEqual(sut.isSpringLoaded, false)
        XCTAssertEqual(sut.preferredStyle, .alert)
        XCTAssertEqual(sut.severity, .critical)
        XCTAssertEqual(sut.message, nil)
        XCTAssertEqual(sut.textFields?.count, 0)
        XCTAssertEqual(sut.actions.count, 0)
        XCTAssertEqual(sut.preferredAction, nil)
        XCTAssertEqual(sut.view.accessibilityIdentifier, String(describing: TestAlerts.nonSpringLoadedAlertCriticalSeverityWithoutMessage))
        
        sut = TestAlerts.nonSpringLoadedActionSheetCriticalSeverityWithMessage.create()
        XCTAssertEqual(sut.title, "Non Spring Loaded - Action Sheet - Critical Severity - With Message")
        XCTAssertEqual(sut.isSpringLoaded, false)
        XCTAssertEqual(sut.preferredStyle, .actionSheet)
        XCTAssertEqual(sut.severity, .critical)
        XCTAssertEqual(sut.message, "Sample message")
        XCTAssertEqual(sut.textFields?.count, 0)
        XCTAssertEqual(sut.actions.count, 0)
        XCTAssertEqual(sut.preferredAction, nil)
        XCTAssertEqual(sut.view.accessibilityIdentifier, String(describing: TestAlerts.nonSpringLoadedActionSheetCriticalSeverityWithMessage))
        
        sut = TestAlerts.nonSpringLoadedActionSheetCriticalSeverityWithoutMessage.create()
        XCTAssertEqual(sut.title, "Non Spring Loaded - Action Sheet - Critical Severity - Without Message")
        XCTAssertEqual(sut.isSpringLoaded, false)
        XCTAssertEqual(sut.preferredStyle, .actionSheet)
        XCTAssertEqual(sut.severity, .critical)
        XCTAssertEqual(sut.message, nil)
        XCTAssertEqual(sut.textFields?.count, 0)
        XCTAssertEqual(sut.actions.count, 0)
        XCTAssertEqual(sut.preferredAction, nil)
        XCTAssertEqual(sut.view.accessibilityIdentifier, String(describing: TestAlerts.nonSpringLoadedActionSheetCriticalSeverityWithoutMessage))
        
        sut = TestAlerts.defaultParameters.create()
        XCTAssertEqual(sut.title, "Default Parameters")
        XCTAssertEqual(sut.isSpringLoaded, true)
        XCTAssertEqual(sut.preferredStyle, .alert)
        XCTAssertEqual(sut.severity, .default)
        XCTAssertEqual(sut.message, nil)
        XCTAssertEqual(sut.textFields?.count, 0)
        XCTAssertEqual(sut.actions.count, 0)
        XCTAssertEqual(sut.preferredAction, nil)
        XCTAssertEqual(sut.view.accessibilityIdentifier, String(describing: TestAlerts.defaultParameters))
        
        let action1 = TestActions.defaultParameters.create()
        let action2 = TestActions.cancelEnabled.create()
        let textFieldHandler: ((UITextField) -> Void) = { _ in }
        sut = TestAlerts.defaultParameters.create(actions: [action1, action2], preferredAction: action2, textFieldHandlers: [textFieldHandler])
        XCTAssertEqual(sut.title, "Default Parameters")
        XCTAssertEqual(sut.isSpringLoaded, true)
        XCTAssertEqual(sut.preferredStyle, .alert)
        XCTAssertEqual(sut.severity, .default)
        XCTAssertEqual(sut.message, nil)
        XCTAssertEqual(sut.textFields?.count, 1)
        XCTAssertEqual(sut.actions.count, 2)
        XCTAssertEqual(sut.preferredAction, action2)
        XCTAssertEqual(sut.view.accessibilityIdentifier, String(describing: TestAlerts.defaultParameters))
    }
}
